# Generated by Django 4.2.5 on 2023-09-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ID',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='No_of_guests',
            field=models.PositiveSmallIntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Inventory',
            field=models.PositiveSmallIntegerField(max_length=5),
        ),
    ]
